require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeuillesController do

  # This should return the minimal set of attributes required to create a valid
  # Feuille. As you add validations to Feuille, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeuillesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all feuilles as @feuilles" do
      feuille = Feuille.create! valid_attributes
      get :index, {}, valid_session
      assigns(:feuilles).should eq([feuille])
    end
  end

  describe "GET show" do
    it "assigns the requested feuille as @feuille" do
      feuille = Feuille.create! valid_attributes
      get :show, {:id => feuille.to_param}, valid_session
      assigns(:feuille).should eq(feuille)
    end
  end

  describe "GET new" do
    it "assigns a new feuille as @feuille" do
      get :new, {}, valid_session
      assigns(:feuille).should be_a_new(Feuille)
    end
  end

  describe "GET edit" do
    it "assigns the requested feuille as @feuille" do
      feuille = Feuille.create! valid_attributes
      get :edit, {:id => feuille.to_param}, valid_session
      assigns(:feuille).should eq(feuille)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Feuille" do
        expect {
          post :create, {:feuille => valid_attributes}, valid_session
        }.to change(Feuille, :count).by(1)
      end

      it "assigns a newly created feuille as @feuille" do
        post :create, {:feuille => valid_attributes}, valid_session
        assigns(:feuille).should be_a(Feuille)
        assigns(:feuille).should be_persisted
      end

      it "redirects to the created feuille" do
        post :create, {:feuille => valid_attributes}, valid_session
        response.should redirect_to(Feuille.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved feuille as @feuille" do
        # Trigger the behavior that occurs when invalid params are submitted
        Feuille.any_instance.stub(:save).and_return(false)
        post :create, {:feuille => {}}, valid_session
        assigns(:feuille).should be_a_new(Feuille)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Feuille.any_instance.stub(:save).and_return(false)
        post :create, {:feuille => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested feuille" do
        feuille = Feuille.create! valid_attributes
        # Assuming there are no other feuilles in the database, this
        # specifies that the Feuille created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Feuille.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => feuille.to_param, :feuille => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested feuille as @feuille" do
        feuille = Feuille.create! valid_attributes
        put :update, {:id => feuille.to_param, :feuille => valid_attributes}, valid_session
        assigns(:feuille).should eq(feuille)
      end

      it "redirects to the feuille" do
        feuille = Feuille.create! valid_attributes
        put :update, {:id => feuille.to_param, :feuille => valid_attributes}, valid_session
        response.should redirect_to(feuille)
      end
    end

    describe "with invalid params" do
      it "assigns the feuille as @feuille" do
        feuille = Feuille.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Feuille.any_instance.stub(:save).and_return(false)
        put :update, {:id => feuille.to_param, :feuille => {}}, valid_session
        assigns(:feuille).should eq(feuille)
      end

      it "re-renders the 'edit' template" do
        feuille = Feuille.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Feuille.any_instance.stub(:save).and_return(false)
        put :update, {:id => feuille.to_param, :feuille => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested feuille" do
      feuille = Feuille.create! valid_attributes
      expect {
        delete :destroy, {:id => feuille.to_param}, valid_session
      }.to change(Feuille, :count).by(-1)
    end

    it "redirects to the feuilles list" do
      feuille = Feuille.create! valid_attributes
      delete :destroy, {:id => feuille.to_param}, valid_session
      response.should redirect_to(feuilles_url)
    end
  end

end
